<template>
  <div class="toolbar"><a-segmented v-model:value="type" :options="[{label:'下载队列',value:'download'},{label:'上传队列',value:'upload'}]"/><a-select v-model:value="status" style="width:130px" :options="statusOptions"/><span class="muted">共 {{total}} 个任务</span><div class="grow"/><a-button @click="toggle">{{running?'暂停队列':'启动队列'}}</a-button><a-button v-if="type==='upload'" @click="action('retry-failed')">重试失败</a-button><a-popconfirm title="确定清理等待中的任务？" @confirm="action('clear-pending')"><a-button>清理等待</a-button></a-popconfirm><a-popconfirm title="确定清理已完成和失败任务？" @confirm="action('clear-success-failed')"><a-button danger>清理已完成</a-button></a-popconfirm></div>
  <a-card class="panel-card"><a-table :loading="loading" :data-source="tasks" :columns="columns" row-key="id" :scroll="{x:850}"><template #bodyCell="{column,record}"><template v-if="column.key==='file'"><strong>{{record.file_name}}</strong><div class="muted">{{record.local_full_path||record.remote_path}}</div></template><template v-if="column.key==='source'">{{record.source||record.source_type||'-'}}</template><template v-if="column.key==='status'"><a-tag :color="colors[record.status]">{{statusLabels[record.status]||'未知'}}</a-tag></template><template v-if="column.key==='size'">{{formatSize(record.file_size||record.size)}}</template></template></a-table></a-card>
</template>
<script setup lang="ts">
import{onMounted,ref,watch}from'vue';import{get,post}from'../../services/http';import{formatSize}from'../../core/format';import type{AnyMap,QueueTask}from'../../types';
const type=ref('download'),status=ref(-1),tasks=ref<QueueTask[]>([]),total=ref(0),running=ref(false),loading=ref(true),statusLabels=['等待中','处理中','已完成','失败','已取消'],colors=['default','processing','success','error','warning'];
const statusOptions=[{value:-1,label:'全部状态'},...statusLabels.map((label,value)=>({value,label}))],columns=[{title:'文件',key:'file'},{title:'来源',key:'source'},{title:'状态',key:'status'},{title:'大小',key:'size'},{title:'错误',dataIndex:'error'}];
async function load(){loading.value=true;try{const[data,run]=await Promise.all([get<AnyMap>(`/${type.value}/queue?page=1&page_size=100&status=${status.value}`),get<boolean>(`/${type.value}/queue/status`)]);tasks.value=data.list||[];total.value=Number(data.total||0);running.value=Boolean(run)}finally{loading.value=false}}
async function action(name:string){await post(`/${type.value}/queue/${name}`,{});await load()}const toggle=()=>action(running.value?'stop':'start');watch([type,status],load);onMounted(load)
</script>
