<template><a-spin :spinning="loading">
  <a-row :gutter="[16,16]"><a-col v-for="item in overviewStats" :key="item.title" :xs="12" :lg="6"><a-card class="stat-card"><a-statistic :title="item.title" :value="item.value" :value-style="{color:item.color}"/><div class="muted">{{item.note}}</div></a-card></a-col></a-row>
  <a-card class="panel-card monitor" title="115 接口监控"><template #extra><a-badge :status="queueStats.is_throttled?'error':'success'" :text="queueStats.is_throttled?'正在限流':'运行正常'"/></template><a-row :gutter="[12,16]"><a-col v-for="item in apiStats" :key="item.title" :xs="12" :md="8" :xl="4"><a-statistic :title="item.title" :value="item.value" :suffix="item.suffix"/></a-col></a-row></a-card>
  <a-row :gutter="[18,18]" style="margin-top:18px"><a-col :xs="24" :xl="17"><a-card class="panel-card" title="同步目录"><template #extra><router-link to="/strm/paths">查看全部</router-link></template><a-table :data-source="paths" :columns="columns" row-key="id" :pagination="false"><template #bodyCell="{column,record}"><template v-if="column.key==='path'"><strong>{{record.remote_path}}</strong><div class="muted">{{record.local_path}}</div></template><template v-if="column.key==='status'"><a-badge :status="record.is_running?'processing':'success'" :text="record.is_running?'运行中':'空闲'"/></template><template v-if="column.key==='time'">{{formatTime(record.last_sync_at as number)}}</template></template></a-table></a-card></a-col><a-col :xs="24" :xl="7"><a-card class="panel-card" title="快速操作"><a-space direction="vertical" style="width:100%"><a-button block size="large" @click="$router.push('/strm/paths')">管理同步目录</a-button><a-button block size="large" @click="$router.push('/scrape/paths')">刮削与整理</a-button><a-button block size="large" @click="$router.push('/system/network')">系统设置</a-button></a-space></a-card></a-col></a-row>
</a-spin></template>
<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{get}from'../services/http';import{formatTime}from'../core/format';import type{Account,AnyMap,SyncPath}from'../types';
const loading=ref(true),paths=ref<SyncPath[]>([]),pathTotal=ref(0),accounts=ref<Account[]>([]),version=ref<AnyMap>({}),queueStats=ref<AnyMap>({});
const columns=[{title:'路径',key:'path'},{title:'来源',dataIndex:'source_type'},{title:'账号',dataIndex:'account_name'},{title:'状态',key:'status'},{title:'最后同步',key:'time'}];
const overviewStats=computed(()=>[{title:'同步目录',value:pathTotal.value,note:`${paths.value.filter(x=>x.enable_cron).length} 个启用定时任务`,color:'#5b6cf9'},{title:'运行任务',value:paths.value.filter(x=>x.is_running>0).length,note:'等待与正在执行',color:'#20a67a'},{title:'网盘账号',value:accounts.value.length,note:`${accounts.value.filter(x=>!x.token_failed_reason).length} 个状态正常`,color:'#8b5fd3'},{title:'系统版本',value:version.value.version||'-',note:`编译日期 ${version.value.date||'-'}`,color:'#e28a38'}]);
const apiStats=computed(()=>[{title:'QPS',value:queueStats.value.qps_count??0},{title:'QPM',value:queueStats.value.qpm_count??0},{title:'QPH',value:queueStats.value.qph_count??0},{title:'平均响应',value:queueStats.value.avg_response_time_ms??0,suffix:'ms'},{title:'总请求',value:queueStats.value.total_requests??0},{title:'限流次数',value:queueStats.value.throttled_count??0}]);
onMounted(async()=>{try{const[p,a,v,q]=await Promise.all([get<AnyMap>('/sync/path-list?page=1&page_size=100'),get<Account[]>('/account/list'),get<AnyMap>('/version'),get<AnyMap>('/115/queue/stats?time_window=3600')]);paths.value=p.list||[];pathTotal.value=p.total??paths.value.length;accounts.value=a;version.value=v;queueStats.value=q}finally{loading.value=false}})
</script><style scoped>.monitor{margin-top:18px}</style>
